export const SagaActions = {
  FETCH_CATEGORIES_ASYNC: "FETCH_CATEGORIES_ASYNC",
  FETCH_PRODUCTS_ASYNC: "FETCH_PRODUCTS_ASYNC",
  LOGIN_USER_REQUEST: "LOGIN_USER_REQUEST",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",
  REGISTER_USER_ASYNC: "REGISTER_USER_ASYNC",
};
